import os
from ics import Calendar, Event
from datetime import datetime

cal = Calendar()
event = Event()
event.name = "Test Calendar Invite"
event.begin = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
event.duration = {"hours": 1}
event.description = "This is a test event generated by Python."
cal.events.add(event)

ics_filename = "test_event.ics"
ics_path = os.path.join(os.getcwd(), ics_filename)
with open(ics_path, 'w') as f:
    f.writelines(cal)

os.startfile(ics_path)
